### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by MaxRei-dev** [Argonne-National-Laboratory/node-red-contrib-modbustcp#24]
hi had trouble making an update. so i startet a new install.
but i got the following error:

`9 Oct 15:45:17 - [info] Installing module: node-red-contrib-modbustcp, version: 1.2.3
9 Oct 15:45:26 - [warn] Installation of module node-red-contrib-modbustcp failed:
9 Oct 15:45:26 - [warn] ------------------------------------------
9 Oct 15:45:26 - [warn] npm ERR! Cannot read property 'match' of undefined
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-10-09T13_45_26_936Z-debug.log
9 Oct 15:45:26 - [warn] ------------------------------------------
`

here the log:

`17 verbose stack TypeError: Cannot read property 'match' of undefined
17 verbose stack     at tarballToVersion (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:87:20)
17 verbose stack     at inflatableChild (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:99:22)
17 verbose stack     at BB.each (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
17 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
17 verbose stack     at Object.gotValue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
17 verbose stack     at Object.gotAccum (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
17 verbose stack     at Object.tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
17 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
17 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
17 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
17 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
17 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
17 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
17 verbose stack     at Immediate.Async.drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
17 verbose stack     at runCallback (timers.js:810:20)
17 verbose stack     at tryOnImmediate (timers.js:768:5)
18 verbose cwd /home/pi/.node-red
19 verbose Linux 4.9.35-v7+
20 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "--save-prefix=~" "--production" "node-red-contrib-modbustcp@1.2.3"
21 verbose node v8.12.0
22 verbose npm  v6.4.1
23 error Cannot read property 'match' of undefined
24 verbose exit [ 1, true ]
`

anyone has an idea ?
thank you

**Comment by MaxRei-dev** [comment]
hi it was npm. fixed it by removing an reinstalling another node.
