### ISSUE TITLE
Full disk with error mesage from mod

### ISSUE THREAD

**Issue by oliveres** [Argonne-National-Laboratory/node-red-contrib-modbustcp#36]
I have full syslog and daemon.log with these repeating messages:

```
Dec 12 13:22:23 nodered Node-RED[1665]: (node:1665) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
Dec 12 13:22:23 nodered Node-RED[1665]:     at processValues (/home/pi/.node-red/node_modules/node-red-contrib-modbustcp/modbustcp.js:342:18)
Dec 12 13:22:23 nodered Node-RED[1665]:     at Timeout._onTimeout (/home/pi/.node-red/node_modules/node-red-contrib-modbustcp/modbustcp.js:381:11)
Dec 12 13:22:23 nodered Node-RED[1665]:     at listOnTimeout (internal/timers.js:554:17)
Dec 12 13:22:23 nodered Node-RED[1665]:     at processTimers (internal/timers.js:497:7)
Dec 12 13:22:23 nodered Node-RED[1665]: (node:1665) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 68289759)
```

**Comment by gr-hayduk** [comment]
I have just installed the module and put simple modbus reads (holding and input regs), started unslave.xyz and the module throws above errors with the spead of light - I have thousands of them.
I think developers of this module shoud take a look on it.
